# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='joiner_id',
            field=models.ManyToManyField(related_name='jointrips', to='app_one.User'),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='app_one.User'),
        ),
    ]
